### ISSUE TITLE
Stop using multiple dockerfiles and start specifying targets for multi-stage builds

### ISSUE THREAD

**Issue by falgon** [falgon/roki-web#589]
- The following two:
    - https://github.com/falgon/roki-web/blob/76bb34fbfd74c2de891cc42cfc965b117fbed95f/docker/contents/Dockerfile
    - https://github.com/falgon/roki-web/blob/76bb34fbfd74c2de891cc42cfc965b117fbed95f/docker/dev/Dockerfile
- Make multi-stage builds happen within the `Dockerfile`, eg.
    ```dockerfile
    FROM ubuntu:24.03 AS base
    # Install dependencies from apt and setup ghcup (do not forget to get chromium browser...)

    # for development...
    FROM base AS dev
    WORKDIR /src
    RUN --mount=type=bind,source=.,dst=.,rw \
        stack --no-terminal --allow-different-user build --only-dependencies
    
    # build stage (for app)
    FROM dev AS build
    WORKDIR /src
    RUN --mount=type=bind,source=.,dst=.,rw \
        mkdir /dist && stack --no-terminal --allow-different-user install --local-bin-path /dist

    # for site and spa
    FROM alpine:latest AS apps
    WORKDIR /app
    RUN apk update && apk upgrade --no-cache && apk add --no-cache gmp-dev libffi-dev zlib-dev chromium
    COPY --from=build /dist/site /app/site
    COPY --from=build /dist/spa /app/spa
    ENV PATH /app:$PATH
    EXPOSE 8888
    ```
    `docker-compose.yml`, eg.
    ```yaml
    services:
        build:
            image: $ROKI_WEB_ENV_IMAGE_NAME $ROKI_WEB_ENV_IMAGE_TAG
            container_name: roki-web-build
            volumes:
                - "../contents:/home/rw-c/bin/contents"
            ports:
                - "8888:8888"
            working_dir: /home/rw-c/bin
            build:
                context: ../
                dockerfile: ./Dockerfile
                target: apps # important
            command: site build --preview
        preview:
            # ditto...
            build:
                context: ../
                dockerfile: ./Dockerfile
                target: apps
            command: site watch --preview --port 8888 --host 0.0.0.0
    # ditto...
    ```
